### ISSUE TITLE
Crash inside React (?)

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#23] opened 2019-02-28 17:34 UTC
Not sure how this happened, and where the code lives. Is this from debug-tools?

`hooks.memoizedState` is `null` but we read `[0]` from it.

You can see the actual hook is the context one. Maybe it's the issue you fixed on master.

<img width="878" alt="screen shot 2019-02-28 at 5 29 43 pm" src="https://user-images.githubusercontent.com/810438/53585942-fbec5b80-3b7e-11e9-98a9-76a75dc0a539.png">

<img width="537" alt="screen shot 2019-02-28 at 5 29 56 pm" src="https://user-images.githubusercontent.com/810438/53585940-fbec5b80-3b7e-11e9-97bc-bb2491367870.png">

<img width="682" alt="screen shot 2019-02-28 at 5 30 13 pm" src="https://user-images.githubusercontent.com/810438/53585939-fbec5b80-3b7e-11e9-9b45-71d07162eada.png">

**Comment by bvaughn** [comment] 2019-02-28 17:36
Yeah, I'm pretty sure that's being caused by what I fixed in facebook/react/pull/14940 (but it hasn't yet been released)

**Comment by bvaughn** [comment] 2019-02-28 21:24
This bug could be reproduced previously by using the browser extension to inspect a component that used a context hook followed by a stateful hook (e.g. state, memo). In the demo, this could be reproduced by selecting the `TreeContextController` node.

I've updated the demo page with an updated version of react (built with facebook/react/pull/14940 and facebook/react/pull/14906) and verified that it's no longer broken.

**Closed by bvaughn** 2019-02-28 21:24 UTC
Labels: bug

**Comment by bvaughn** [comment] 2019-02-28 22:27
I also added an integration test to react [d450ead](https://github.com/facebook/react/pull/14906/commits/d450ead132f9caec0407c303c8f71b3d36c518e8) to help guard against this regression.
