### ISSUE TITLE
chrome doesn't allow to enable it

### ISSUE THREAD

**Issue by hakankaraduman** [bvaughn/react-devtools-experimental#291] opened 2019-05-27 12:32 UTC
I followed the installation instructions but chrome doesn't allow me to enable it because it was not installed from the chrome extension store. 

I removed stable devtools from extensions before installing this, still the same.

**Comment by bvaughn** [comment] 2019-05-27 16:10
The beta release isn't something I have bandwidth to support and troubleshoot. Seems like Chrome's support for self hosted extensions is not that great, but unfortunately I don't think there's anything I can do about it.

All I can say is that I'm working to get this into the store as quickly as possible so people won't need to side load. In the meanwhile, I'm going to close this issue since it's not really actionable. Sorry @hakankaraduman!

Possible duplicate of #286

**Closed by bvaughn** 2019-05-27 16:10 UTC

**Comment by hakankaraduman** [comment] 2019-05-27 16:28
I understand, sorry if what I'm asking is basic. I'm trying to understand and learn this situation. Is there a way I can replicate what you do to use this package as is. Like, what are the steps you do to test your development? If there is a name for this process, if you can tell me, I can search on the internet.

I'm not expecting you to spend time and write a guide, thanks anyway.

**Comment by bvaughn** [comment] 2019-05-28 14:43
The instruction installations I wrote in the README are the exact ones I followed to install the extension: https://github.com/bvaughn/react-devtools-experimental#installation

**Comment by vnvizitiu** [comment] 2019-05-28 14:48
I managed to install in in chrome by loading unpackaged

**Comment by bvaughn** [comment] 2019-05-28 15:47
I updated the Chrome installation to use a packed extension (ZIP) format rather than CRX (611fe48). Hopefully this might work for more people.

**Comment by hakankaraduman** [comment] 2019-05-29 09:48
Thank you very much for your time, it worked this way.

**Comment by bvaughn** [comment] 2019-05-29 14:53
Glad to hear~
