### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by affanshahid** [bvaughn/react-devtools-experimental#314] opened 2019-06-10 21:16 UTC
I am using [React Apollo Hooks](https://github.com/trojanowski/react-apollo-hooks) in one of my apps, whenever I select (in the components tab) a component which uses a useQuery hook, I get the following:

![image](https://user-images.githubusercontent.com/17955210/59227405-ba903100-8bee-11e9-85fd-1c4621661f40.png)

Ext Version: b3046c6 (6/8/2019)
Chrome: 74.0.3729.169

**Comment by bvaughn** [comment] 2019-06-10 21:18
Please share a repro case with e.g. Code Sandbox?

Also please specify which React version you're using.

**Comment by bvaughn** [comment] 2019-06-13 14:06
Closing due to lack of info.

Seems likely this is a duplicate of #23 and can be fixed by updating the version of React to include the bug fix added in [v16.8.4](https://github.com/facebook/react/releases/tag/v16.8.4).

**Closed by bvaughn** 2019-06-13 14:06 UTC
Labels: 👀 needs info
