### ISSUE TITLE
Re-enable postMessage transferable for faster ArrayBuffer transfers

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#25] opened 2019-03-01 13:16 UTC
I got this on FB.com sandbox:

<img width="815" alt="screen shot 2019-03-01 at 1 15 24 pm" src="https://user-images.githubusercontent.com/810438/53640457-26dcbb00-3c24-11e9-828f-a987ffeec4da.png">

**Comment by bvaughn** [comment] 2019-03-01 15:49
Hey Dan. Any info about what you were doing when this happened? (Any breakpoints set or anything?) Can you reproduce it?

**Comment by gaearon** [comment] 2019-03-01 16:03
Nope, just happened randomly. :-(

**Comment by bvaughn** [comment] 2019-03-01 16:14
Damn!

I've seen this one before, but only when I had breakpoints set in Chrome.

I guess I should just comment out the transferrables approach for now since Chrome doesn't let me actually transfer the array buffer anyway. That sucks.

**Comment by bvaughn** [comment] 2019-03-01 16:49
How often are you able to trigger this? (If I thought I had a fix– which I don't, but if I did– would you be able to say with any confidence that it worked? or is it a rare error for you?)

**Comment by bvaughn** [comment] 2019-03-01 16:57
Regarding transferables, the [`postMessage` docs](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage) say:
> An optional array of Transferable objects to transfer ownership of. If the ownership of an object is transferred, it becomes unusable (neutered) in the context it was sent from and becomes available only to the worker it was sent to.

So it seems like either Chrome has a bug or (probably more likely) some part of the DevTools code is trying to touch the array buffer somehow _after_ it's been sent across the bridge. I'm not sure how this is happening though, because the flow of code is:

* [`renderer` passes the array to the `agent` and _immediately_ clears its reference](https://github.com/bvaughn/react-devtools-experimental/blob/8aa6f96279700ce75a1980f4cad97bafdc36eaa5/src/backend/renderer.js#L541-L542)
* [`Agent` passes the array on to the `Bridge`](https://github.com/bvaughn/react-devtools-experimental/blob/8aa6f96279700ce75a1980f4cad97bafdc36eaa5/src/backend/agent.js#L202-L208) but otherwise does nothing with it
* [`Bridge` passes it to the "wall", maybe after a small delay](https://github.com/bvaughn/react-devtools-experimental/blob/8aa6f96279700ce75a1980f4cad97bafdc36eaa5/src/bridge.js#L30-L50)– but it has not yet been serialized at this point so the delay should be okay
* ["wall" passes it to `postMessage` as-is](https://github.com/bvaughn/react-devtools-experimental/blob/8aa6f96279700ce75a1980f4cad97bafdc36eaa5/shells/browser/shared/src/main.js#L43-L47)

I'm not sure where in this flow of code we would be touching the array in any way after it had been neutered.

**Comment by bvaughn** [comment] 2019-03-06 21:18
I've commented out the transferrable for now (c184493) which should avoid this issue. Would still like to figure out the cause so we can re-enable it for Firefox.

**Comment by gaearon** [comment] 2019-03-06 22:57
Can we do `if (!window.chrome)` or something?

**Comment by sompylasar** [comment] 2019-04-28 20:09
This may potentially be fixed with this cleanup: https://github.com/bvaughn/react-devtools-experimental/pull/229

**Comment by bvaughn** [comment] 2019-08-19 22:29
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been relocated to:
https://github.com/facebook/react/issues/16488

**Closed by bvaughn** 2019-08-19 22:29 UTC
Labels: ⏱️  performance, 👋 help wanted, 😭 bug
