### ISSUE TITLE
Add new Props and new State keys [ Feature Request ]

### ISSUE THREAD

**Issue by goxr3plus** [bvaughn/react-devtools-experimental#358] opened 2019-08-01 10:24 UTC
This is still missing in https://github.com/facebook/react-devtools but i don't see it neither here 

For example on the right panel :

![image](https://user-images.githubusercontent.com/20374208/62286017-82270980-b45f-11e9-97ec-9e84f79c620d.png)

instead of only being able to edit the props and state we should be able to add new key/values to them :) Pretty useful feature actually .

Is it hard to implement ? :) ?

**Comment by bvaughn** [comment] 2019-08-01 14:16
Duplicate of #300

**Closed by bvaughn** 2019-08-01 14:16 UTC
