### ISSUE TITLE
Selection doesn't get preserved first time after switching the filter

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#254] opened 2019-05-02 01:06 UTC
1. Change filters
2. Select any component
3. Reload after a second

Expected: component selection is restored.
Actual: it only gets persisted after another reload.

![](https://d3r69eeiwn2k86.cloudfront.net/items/2H3x06360V0v2I3a2R0O/Screen%20Recording%202019-05-02%20at%2002.05%20am.gif?v=d4c99cd6)

**Comment by bvaughn** [comment] 2019-05-02 22:18
Ah, the problem is that unmounting and re-mounting the roots cause our pseudo key counter to be incremented.

**Comment by bvaughn** [comment] 2019-05-02 22:21
Fixed via 4bf3ac1. Not sure how best to capture in a test, yet.

**Closed by bvaughn** 2019-05-02 22:21 UTC
Labels: 😭 bug

**Comment by gaearon** [comment] 2019-05-02 23:49
Ah makes sense.
