### ISSUE TITLE
Error: "getCommitTree(): Unable to reconstruct tree for root "1" and commit 60"

### ISSUE THREAD

**Issue by sebmarkbage** [bvaughn/react-devtools-experimental#146] opened 2019-04-12 23:05 UTC
In the Profiler tab. Profile + Reload. Select the commit list. Hit the right-key which quickly jumps from commit to commit. When I get close to the edge I get this error.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.0-2636142

Call stack: at P (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:56:115611)
    at e.getCommitTree (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:56:121688)
    at Ta (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:56:233290)
    at Wo (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:52971)
    at Ea (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:59795)
    at Sa (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:66478)
    at Vi (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:86476)
    at Wi (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:86866)
    at kl (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:92864)
    at yl (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:92106)

Component stack: in Ta
    in Suspense
    in div
    in div
    in div
    in Oi
    in ra
    in Unknown
    in n
    in Unknown
    in div
    in div
    in ia
    in He
    in $e
    in Gi

**Comment by bvaughn** [comment] 2019-04-13 00:26
Nice! Our first error boundary bug! Thanks

**Comment by bvaughn** [comment] 2019-04-14 00:57
I've been able to reproduce this. At least in the case I'm looking at, the [profiling summary](https://github.com/bvaughn/react-devtools-experimental/blob/master/OVERVIEW.md#profiling-summary) returned by the backend says it has 27 commit times and durations, but the `profilingOperations` (a `Map` of root (id) to a list of tree mutations that occur during profiling) only has 23 entries.

I'm not  sure why this mismatch is happening. When profiling, we send an "operations" message even if there were no mutations to the tree:
https://github.com/bvaughn/react-devtools-experimental/blob/00f6466ec1a7f7dbcc2aef570d55e6ace113ebcf/src/backend/renderer.js#L599-L606

Hmm... I must be overlooking something.

At least on the internal (FB) app that I'm profiling, the error seems to happen consistently on the 24th commit. 🤔

**Comment by bvaughn** [comment] 2019-04-14 01:10
Ah, I think I might know what the cause is.

I _think_ it's a race between when the frontend and backend each think profiling has stopped. For the frontend, profiling stops when you click the record button- but with certain apps (that commit tons of small commits, like a certain internal FB app I'm testing)- a few additional commits might squeeze through before the frontend's message comes through to notify the backend that profiling is done.

At this point, the set of commits each side thinks occurred during  the  most recent profiling session is off by a few.

**Comment by bvaughn** [comment] 2019-04-14 01:32
Fixed in b76372c. Just deployed a new extension build.

**Closed by bvaughn** 2019-04-14 01:32 UTC
Labels: 😭 bug
