### ISSUE TITLE
Hook names grabbing solution w/o changing api

### ISSUE THREAD

**Issue by a-x-** [bvaughn/react-devtools-experimental#373] opened 2019-08-09 10:24 UTC
add to react jsx babel transformation minor version with grabber assosiated with hooks const names.

It's dead easy, I can create a demo.

```js
const [data, updData] = useState(null);
```
would be something like:
```js
const [data, updData] = useState(null);
__devtools_reportHookName(data, 'data'); // data is a pointer to some Map storage under the hook of devtools
```

**Comment by bvaughn** [comment] 2019-08-09 15:41
Duplicate of #323

**Closed by bvaughn** 2019-08-09 15:41 UTC
