### ISSUE TITLE
Components tree is sometimes unexpectedly empty after navigation

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#217] opened 2019-04-23 18:29 UTC
1. Open FB page
2. Open Components tab
3. Change address bar to `https://reactjs.org` and press Enter

Expected: Components tab gets populated.
Actual:

<img width="783" alt="Screen Shot 2019-04-23 at 7 27 37 PM" src="https://user-images.githubusercontent.com/810438/56606380-00247a80-65fe-11e9-988c-2ad3e69eb579.png">

~~If I **inspect background page**, I see this:~~ (fixed by #229)

<img width="652" alt="Screen Shot 2019-04-23 at 7 27 12 PM" src="https://user-images.githubusercontent.com/810438/56606408-0b77a600-65fe-11e9-9f65-5502401b7e4a.png">

**Comment by sompylasar** [comment] 2019-04-26 11:31
Please see https://github.com/bvaughn/react-devtools-experimental/pull/229

**Comment by bvaughn** [comment] 2019-04-30 16:21
I don't think #229 completely resolves this issue. We no longer error, which is good. But the Components tree is usually empty after navigating to reactjs.org.

**Comment by sompylasar** [comment] 2019-04-30 18:47
> But the Components tree is usually empty after navigating to reactjs.org.

Wow, would you please share a repro, maybe a screen recording? I didn't see that.

**Comment by bvaughn** [comment] 2019-05-23 17:14
While working on #235 I observed that this behavior is pretty easy to reproduce after going to an internal FB SSR site and then navigating to react-window.now.sh. Doesn't happen _every_ time but happens _most_ times that I need to reload the page after navigating in this case.

**Comment by bvaughn** [comment] 2019-05-23 17:37
I've observed that I can reliably navigate between [react-window.now.sh](https://react-window.now.sh) and [bvaughn.github.io/react-virtualized](http://bvaughn.github.io/react-virtualized) and the Components tab is never empty. Seems like I can add [reactjs.org](https://reactjs.org) into that mix too and things work okay.

But when I add Facebook (FB5) into the mix and then navigate to [react-window.now.sh](https://react-window.now.sh), the tree is pretty reliably empty.

**Comment by bvaughn** [comment] 2019-05-23 18:31
Looks like the comment in this line is not accurate:
https://github.com/bvaughn/react-devtools-experimental/blob/34f6fa4fab502497b6ffd5d04cf0547bb9569fc2/shells/browser/shared/src/main.js#L66-L70

**Comment by sompylasar** [comment] 2019-05-23 19:28
I've also seen some warnings "shutdown" on a destroyed bridge.

There are most likely race conditions between navigation events, messages, and port destruction.

**Comment by bvaughn** [comment] 2019-05-23 21:50
I wish it were easier to debug extensions with port issues like this.

**Comment by sompylasar** [comment] 2019-05-23 22:31
Yeah. I think we may benefit from remodeling the events we get from the browser from callbacks and shared mutable state into some kind of event stream and a state reducer.

**Comment by bvaughn** [comment] 2019-05-23 22:32
No idea what you mean by that.

**Comment by sompylasar** [comment] 2019-05-24 03:24
I mean handle browser events more declaratively and explicitly. Instead of handling like this:
```
let something;
onBrowserNewTab(() => {
  something = new Something();
});
onBrowserNavigated(() => {
  something.send("shutdown");
});
```

Have something like:
```
let state = "initial";
function reducer(event) {
  if (state === "initial") {
    if (event === "newtab") {
      return "mounting";
    } else if (event === "navigated") {
      throw new Error("unexpected " + event + " in " + state);
    } else {
      throw new Error("unexpected " + event + " in " + state);
    }
  } else if (state === "mounting") {
    // ... 
  } else if (state === "mounted") {
    // ... 
  } else if (state === "navigating") {
    // ... 
  } else {
    throw new Error("impossible");
  }
}
onBrowserNewTab(() => {
  state = reducer("newtab");
});
onBrowserNavigated(() => {
  state = reducer("navigated");
});
```

Sorry for sloppiness, typing from phone.

**Comment by gaearon** [comment] 2019-05-24 23:29
Yep that sounds like the way to go

**Comment by bvaughn** [comment] 2019-05-25 14:15
If all of the "state" was collocated, that would make sense to me- but there are several walls/bridges/post spread across separate contexts (content script, page, backend). I guess I'm not sure what you're proposing specifically.

Interested in posting a PR?

**Comment by sompylasar** [comment] 2019-05-25 17:35
As these contexts communicate with messages, each of them would be designed as a separate state machine, with messages as events to that state machine, in addition to the browser "messages" (call backs).

**Comment by sompylasar** [comment] 2019-05-25 17:36
> Interested in posting a PR?

Maybe, it's a long weekend.

**Comment by bvaughn** [comment] 2019-05-26 22:13
I guess I don't see how separate state machines will help simplify the problem of detecting when to disconnect ports. 😄 If you'd like to put together a PR at some point, please do.

**Comment by sompylasar** [comment] 2019-05-26 22:39
> I guess I don't see how separate state machines will help simplify the problem of detecting when to disconnect ports. 😄 If you'd like to put together a PR at some point, please do.

It's not necessary to build all of them now, it's enough to build the one that manages the context about onNavigated and the port. I meant to say that to cover the entire state of all components that you mentioned you'd need one for each separate context that communicates with other ones via async messaging.

**Comment by bvaughn** [comment] 2019-08-19 22:28
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been relocated to:
https://github.com/facebook/react/issues/16495

**Closed by bvaughn** 2019-08-19 22:28 UTC
Labels: 😭 bug
