### ISSUE TITLE
Keyboard navigation is buggy with filters

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#253] opened 2019-05-02 01:04 UTC
1. Filter out function components in the fixture
2. Try to navigate tree with keyboard, including expanding and pressing down

It jumps between nodes unexpectedly:

![](https://d3r69eeiwn2k86.cloudfront.net/items/10411q0i0M353Y383O0l/Screen%20Recording%202019-05-02%20at%2002.03%20am.gif?v=f9fa444f)

**Comment by bvaughn** [comment] 2019-05-02 01:47
ooh, this is an interesting one that I did not think to test for. Nice find.

**Comment by bvaughn** [comment] 2019-05-02 01:58
can you clarify which key you're pressing them it jumps: up or left?

**Comment by bvaughn** [comment] 2019-05-02 21:47
I don't think this is actually caused by filters, but by multiple first-level children within a root. I think this throws off our index calculation. I'll add some tests for this.

**Comment by bvaughn** [comment] 2019-05-02 21:59
Yup. This test catches the failure.
<img width="565" alt="Screen Shot 2019-05-02 at 2 59 34 PM" src="https://user-images.githubusercontent.com/29597/57109662-ed3f3380-6cea-11e9-814d-41492aeb11c7.png">

**Comment by bvaughn** [comment] 2019-05-02 22:13
Test added and bug fixed via d7447a8

**Closed by bvaughn** 2019-05-02 22:13 UTC
Labels: 😭 bug
