### ISSUE TITLE
Breadcrumbs are obscured by the scroll

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#15] opened 2019-02-27 17:13 UTC
I love this mode but it's pretty hard to click and not land on the scrollbar.

<img width="641" alt="screen shot 2019-02-27 at 5 12 09 pm" src="https://user-images.githubusercontent.com/810438/53509095-06412380-3ab3-11e9-8bf0-6d617be41d83.png">

**Comment by bvaughn** [comment] 2019-02-27 17:16
Duplicate of #7

**Closed by bvaughn** 2019-02-27 17:16 UTC
